### ISSUE TITLE
Provide the ability to set arbitrary headers for the websocket client

### ISSUE THREAD

**Issue by dehort** [project-receptor/python-receptor#151]
It would be nice to be able to set headers that would be used when making the initial connection to a ws:// or wss:// peer.

**Comment by matburt** [comment]
Implemented in #161

**Comment by elyezer** [comment]
I was not able to verify this, I tried to do the following:

First I started a node listening for WebSocket connections:

```console
$ receptor --debug --node-id=controller -d /tmp/controller node --listen=ws://127.0.0.1:9999
INFO 2020-03-30 16:38:13,950 controller entrypoints Running as Receptor node with ID: controller
INFO 2020-03-30 16:38:13,951 controller controller Serving on ws://127.0.0.1:9999
DEBUG 2020-03-30 16:39:28,049 controller base Unencrypted connection with ('127.0.0.1', 44482).
DEBUG 2020-03-30 16:39:28,049 controller base waiting for HI
DEBUG 2020-03-30 16:39:28,052 controller receptor Emitting Route Advertisements, excluding set()
DEBUG 2020-03-30 16:39:28,053 controller base starting normal loop
DEBUG 2020-03-30 16:39:28,054 controller receptor spawning message_handler
DEBUG 2020-03-30 16:39:28,054 controller base Watching queue <receptor.connection.ws.WebSocket object at 0x7ff25e93ac10>
DEBUG 2020-03-30 16:39:28,056 controller receptor Emitting Route Advertisements, excluding {'controller', '50eacf73-59d5-4a3d-841c-d3351f29e9f9'}
ERROR 2020-03-30 16:39:33,143 controller base watch_queue: error getting data from buffer
Traceback (most recent call last):
  File "/home/elyezer/code/receptor/receptor/receptor/connection/base.py", line 102, in watch_queue
    item = await asyncio.wait_for(self.outbound.get(), 5.0)
  File "/usr/lib64/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError
INFO 2020-03-30 16:39:38,146 controller receptor Removing connection <receptor.connection.ws.WebSocket object at 0x7ff25e93ac10> for node 50eacf73-59d5-4a3d-841c-d3351f29e9f9
DEBUG 2020-03-30 16:39:38,146 controller receptor Removing ephemeral node 50eacf73-59d5-4a3d-841c-d3351f29e9f9
INFO 2020-03-30 16:39:38,147 controller receptor Expiring connection 50eacf73-59d5-4a3d-841c-d3351f29e9f9
DEBUG 2020-03-30 16:39:38,151 controller receptor Emitting Route Advertisements, excluding set()
DEBUG 2020-03-30 16:39:38,153 controller receptor message_handler: cancel request received
```

The failure above happened when the following was done:

```console
$ receptor -d /tmp/ping ping foo --peer ws://localhost:9999 --ws_extra_header=x-special-auth:supersecret --ws_extra_header=foo:bar

Connection timed out. Exiting.
ERROR 2020-03-30 16:39:33,070  base watch_queue: error getting data from buffer
Traceback (most recent call last):
  File "/home/elyezer/code/receptor/receptor/receptor/connection/base.py", line 102, in watch_queue
    item = await asyncio.wait_for(self.outbound.get(), 5.0)
  File "/usr/lib64/python3.7/asyncio/tasks.py", line 435, in wait_for
    await waiter
concurrent.futures._base.CancelledError
```

With that I am not sure if the header was really sent or if receptor is not currently able to deal with web sockets.

@matburt or @ghjm could any of you provide more information here please? Am I doing something wrong?

**Comment by ghjm** [comment]
It looks to me like the problem is that you start your node with `--node-id=controller` but then are doing `ping foo` so unless the `controller` node knows about a different `foo` node on the Receptor mesh, it's expected that this would time out.

The `concurrent.futures._base.CancelledError` is a different issue - when a connection closes you sometimes get this traceback.

**Comment by elyezer** [comment]
@ghjm thanks for the clarification it helped me verifying this.

I've got the ping to the proper node and I was able to verify that the headers were sent as expected:

```
12:50:56.509293 IP (tos 0x0, ttl 64, id 30060, offset 0, flags [DF], proto TCP (6), length 327)
    localhost.49366 > localhost.distinct: Flags [P.], cksum 0xff3b (incorrect -> 0x4227), seq 0:275, ack 1, win 512, options [nop,nop,TS val 779500013 ecr 779500012], length 275
E..Gul@.@..B..........'.......cX.....;.....
.v9..v9.GET / HTTP/1.1
Host: localhost:9999
x-special-auth: supersecret
foo: bar
Upgrade: WebSocket
Connection: Upgrade
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: ztS5G5BtytyXu4LM5ACfWQ==
Accept: */*
Accept-Encoding: gzip, deflate
User-Agent: Python/3.8 aiohttp/3.6.2
```

With that we can consider this as being verified.
