### ISSUE TITLE
Receptor continues running if unable to bind to listen socket address

### ISSUE THREAD

**Issue by jeremy-audet** [project-receptor/python-receptor#152]
If I start two receptor processes and tell them to bind on the same socket address (by default: 8888), then one will bind, and the other will emit an error about being unable to bind but continue running.

```console
$ poetry run receptor --data-dir="$(mktemp --directory)" node
```

```console
$ poetry run receptor --data-dir="$(mktemp --directory)" node
ERROR 2020-03-05 13:57:20,800  controller [Errno 98] error while attempting to bind on address ('0.0.0.0', 8888): address already in use
Traceback (most recent call last):
  File "/home/ichimonji10/code/receptor/receptor/controller.py", line 46, in exit_on_exceptions_in
    await task
  File "/usr/lib/python3.8/asyncio/streams.py", line 94, in start_server
    return await loop.create_server(factory, host, port, **kwds)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1459, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 8888): address already in use
```

It's true that some network connectivity issues are unavoidable. For example, the peer specified by the `--peer` argument might be unavailable. But for me, there's a big difference between "the process can't bind to a  socket address" and "the process can't contact a socket address." The former should cause a catastrophic failure for a server, the latter not.

**Comment by jeremy-audet** [comment]
Duplicate of #133.
